version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: synapse_kms_postgres_prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - synapse_kms_pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  synapse_kms_pgdata_prod:
